# Generated by Django 5.1.3 on 2024-11-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
