# Generated by Django 5.1.3 on 2024-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pizza')),
                ('size', models.IntegerField(choices=[(20, 'Маленькая'), (30, 'Средняя'), (35, 'Большая')], default=20, verbose_name='Размер')),
                ('weight', models.IntegerField(blank=True, default=400, null=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='pizza.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
