# Generated by Django 5.1.3 on 2024-11-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_ingredient_pizza_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
