# Generated by Django 5.1.3 on 2024-11-25 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('transport', models.IntegerField(choices=[(1, 'Пешком'), (2, 'Самокат'), (3, 'Автомобиль')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Отменен'), (1, 'В обработке'), (2, 'Повара готовят'), (3, 'В пути к вам'), (4, 'Заказ доставлен')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, 'Заказ оплачен'), (2, 'Не оплачен')], default=2)),
                ('payment_type', models.IntegerField(choices=[(1, 'Картой на сайте'), (2, 'Оплата при получении')], default=2)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address_orders', to='users.address')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='delivery.courier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
